apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: apps-foobar
  namespace: rook-ceph
spec:
  bucketName: apps-foobar
  storageClassName: ceph-s3
  additionalConfig:
    # maxObjects: "1000000"
    maxSize: 256G
