apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-s3
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
parameters:
  objectStoreName: s3
  objectStoreNamespace: rook-ceph
