version: "3.7"

services:
  jupyter:
    image: hub.teko.vn/data/pyspark-notebook:2.4.4-hadoop-3.2.1
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    user: root
    ports:
    - 8888:8888
    - 4040:4040 # spark app
    volumes:
    - ./work:/home/jovyan/work

  mysql:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - ./sample/mysql/:/docker-entrypoint-initdb.d/
    - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    command: [server, /data]
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: SuperSecr3t
    ports:
    - 9000:9000
    volumes:
    - minio_data:/data

volumes:
  mysql_data:
  minio_data:
